name: Deploy to S3

on:
  push:
    branches:
      - main  # or your deployment branch

env:
  AWS_ACCESS_KEY_ID: "AKIA6GBMCSOG2G6ERHUS"
  AWS_SECRET_ACCESS_KEY: "px9wYUa+tFFOVh1bMwoUyxQW2ENPj0ONzGIsCsYw"
  AWS_REGION: "ap-south-1"
  S3_BUCKET: "bravo-static-bucket1"
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Sync files to S3
        run: |
          aws s3 sync . s3://${{ secrets.S3_BUCKET }} \
            --delete \
            --exclude ".git/*" \
            --exclude ".github/*"
